# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('sub_major', models.CharField(blank=True, max_length=30)),
                ('grade', models.CharField(choices=[('freshman', '1학년'), ('sophomore', '2학년'), ('junior', '3학년'), ('senior', '4학년')], max_length=10)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='menotor/profile/%Y/%m/%d')),
                ('intro', models.TextField()),
            ],
        ),
    ]
