# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lattors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30, unique=True, verbose_name='전공')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('tel', models.CharField(max_length=20, verbose_name='전화번호')),
                ('addr', models.CharField(max_length=100, verbose_name='주소')),
                ('school', models.CharField(max_length=30, verbose_name='고등학교')),
                ('school_type', models.CharField(choices=[('일반', '일반 인문계 고등학교'), ('외고', '외국어 고등학교'), ('과고', '과학 고등학교'), ('자사고', '자율형 사립고등학교'), ('자율고', '자율형 공립고등학교'), ('실업계', '실업계/전문 고등학교')], max_length=20, verbose_name='학교 유형')),
                ('grade', models.CharField(choices=[('first', '1학년'), ('second', '2학년'), ('third', '3학년')], max_length=10, verbose_name='학년')),
                ('school_expect', models.CharField(max_length=30, verbose_name='희망 대학교')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='mentee/profile/%Y/%m/%d', verbose_name='프로필 사진')),
                ('intro', models.TextField(verbose_name='소개글')),
                ('major_expect', models.ManyToManyField(to='lattors.Major', verbose_name='희망 전공')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='mentor',
            name='addr',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='grade',
            field=models.CharField(choices=[('freshman', '1학년'), ('sophomore', '2학년'), ('junior', '3학년'), ('senior', '4학년')], max_length=10, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='intro',
            field=models.TextField(verbose_name='소개글'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='major',
            field=models.CharField(max_length=30, verbose_name='주전공'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='menotor/profile/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='school',
            field=models.CharField(max_length=30, verbose_name='대학교'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='sub_major',
            field=models.CharField(blank=True, max_length=30, verbose_name='복수/부전공'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
    ]
