# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lattors', '0004_mentor_hits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentor',
            new_name='Mentors',
        ),
    ]
