# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattors', '0007_auto_20171016_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actphoto',
            name='year',
            field=models.CharField(default=2017, max_length=10, verbose_name='활동 년도'),
        ),
    ]
