# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 08:35
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lattors', '0008_auto_20171016_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actphoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='actphoto', verbose_name='활동 사진'),
        ),
    ]
