# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattors', '0009_auto_20171016_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actphoto',
            name='year',
            field=models.CharField(choices=[('2017', '2017년'), ('2016', '2016년'), ('2015', '2015년'), ('2014', '2014년'), ('2013', '2013년 이전')], default=2017, max_length=10, verbose_name='활동 년도'),
        ),
    ]
