# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lattors.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171018_2205'),
        ('lattors', '0013_auto_20171020_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkMentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100, validators=[lattors.models.min_length_3_validator], verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
