# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('tel', models.CharField(max_length=20, verbose_name='전화번호')),
                ('addr', models.CharField(max_length=100, verbose_name='주소')),
                ('school', models.CharField(max_length=30, verbose_name='대학교')),
                ('major', models.CharField(max_length=30, verbose_name='주전공')),
                ('sub_major', models.CharField(blank=True, max_length=30, verbose_name='복수/부전공')),
                ('grade', models.CharField(choices=[('freshman', '1학년'), ('sophomore', '2학년'), ('junior', '3학년'), ('senior', '4학년')], max_length=10, verbose_name='학년')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='menotor/profile/%Y/%m/%d', verbose_name='프로필 사진')),
                ('intro', models.TextField(verbose_name='소개글')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
