# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='홍길동', max_length=10, validators='user_validator', verbose_name='이름'),
        ),
    ]
