# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20171018_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='홍길동', max_length=10, validators='user_validator', verbose_name='이름')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('emailadress', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
