# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171018_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emailadress',
            new_name='emailaddress',
        ),
    ]
