# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171021_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adminmentor',
            field=models.BooleanField(default=False, verbose_name='멘토등록 여부'),
        ),
    ]
